name: fuellogic
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  svg_flutter: ^0.0.1
  cached_network_image: ^3.4.1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  get: ^4.7.2
  cloud_firestore: ^5.6.9
  awesome_dialog: ^3.2.1
  google_fonts: ^6.2.1
  package_rename: ^1.10.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  icons_plus: ^5.0.0
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  firebase_messaging: ^15.2.9
  app_settings: ^6.1.1
  flutter_local_notifications: ^19.3.0
  http: ^1.4.0
  googleapis_auth: ^2.0.0
  webview_flutter: ^4.13.0


dependency_overrides:
  web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/jsons/
    - assets/html/


  
  

  
  

  
  
  
  
  
  fonts:
    - family: Public-Bold
      fonts:
        - asset: assets/fonts/PublicSans-Bold.otf
    - family: Public-Regular
      fonts:
        - asset: assets/fonts/PublicSans-Regular.otf
    - family: Public-SemiBold
      fonts:
        - asset: assets/fonts/PublicSans-SemiBold.otf
    - family: PublicSans-BoldItalic
      fonts:
        - asset: assets/fonts/PublicSans-BoldItalic.otf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.otf
    - family: Inter-Medium-Italic
      fonts:
        - asset: assets/fonts/Inter-MediumItalic.otf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.otf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.otf

  
  


package_rename_config:
  android:
    app_name: Fuelogic
    package_name: com.codetrail.fuelogic

  ios:
    app_name: Fuelogic
    bundle_name: fuelogic
    package_name: com.codetrail.fuelogic